services:
  graph-db:
    image: neo4j:5.26.8
    ports:
      - "7687:7687" # for Neo4j driver
      - "7474:7474" # for Neo4j browser
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs:
