package edu.mimuw.sovaide.domain.plugin.frontend;

import java.util.Map;

/**
 * Contains data and configuration for a GUI component generated by a plugin.
 * <p>
 * The {@code componentType} determines how the data is presented in the frontend.
 * Refer to {@link FrontendComponentType} for supported types and expected data.
 */
public record GuiComponentData(
		FrontendComponentType componentType,
		Map<String, Object> data,
		Map<String, Object> config
) {}
